
create schema mrspo_schema;

create table products
(
    price       double precision,
    quantity    integer,
    created_at  timestamp(6) with time zone not null,
    id          bigint generated by default as identity
        primary key,
    updated_at  timestamp(6) with time zone not null,
    name        varchar(255)
);

create table users
(
    created_at  timestamp(6) with time zone not null,
    id          bigint generated by default as identity
        primary key,
    updated_at  timestamp(6) with time zone not null,
    authorities varchar(255),
    password    varchar(255)                not null,
    username    varchar(255)                not null
        unique
);